# Generated by Django 4.1.3 on 2022-11-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='accepted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
